[server]
address = ":5354"
domain = "dns.toys"


[timezones]
enabled = true

# Path to the geo location file from geonames.org
# Directory: http://download.geonames.org/export/dump/
geo_filepath = "cities15000.txt"


[fx]
enabled = false

# Frequency to refresh the currency conversion data from the API.
refresh_interval = "6h"

snapshot_enabled = true
snapshot_file = "fx.dump"


[myip]
enabled = true


[weather]
enabled = true

# Max forecast days to store.
max_entries = 3

cache_ttl = "1h"

# Useragent for the yr.no API
useragent = "github.com/knadh/dns.toys"

snapshot_enabled = true
snapshot_file = "weather.dump"


[units]
enabled = true
